# Generated by Django 5.0.4 on 2025-10-27 11:31

from django.db import migrations


def create_unique_brands(apps, schema_editor):
    ShoeModel = apps.get_model('main_app', 'Shoe')
    UniqueBrandModel = apps.get_model('main_app', 'UniqueBrands')

    unique_brands = ShoeModel.objects.values_list('brand', flat=True).distinct()

    unique_brands_to_create = [UniqueBrandModel(brand=b) for b in unique_brands]
    UniqueBrandModel.objects.bulk_create(unique_brands_to_create)


def reverse_unique_brands(apps, schema_editor):
    UniqueBrandModel = apps.get_model('main_app', 'UniqueBrands')
    UniqueBrandModel.objects.all().delete()

class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_uniquebrands'),
    ]

    operations = [
        migrations.RunPython(
            code=create_unique_brands,
            reverse_code=reverse_unique_brands
        ),
    ]
