# Generated by Django 5.0.4 on 2025-10-28 00:38

from django.db import migrations
from django.db.models import When, Case, Value, CharField


def set_age_group(apps, schema_editor):
    PersonModel = apps.get_model("main_app", "Person")

    PersonModel.objects.update(
        age_group=Case(
            When(age__lt=13, then=Value("Child")),
            When(age__lt=18, then=Value("Teen")),
            default=Value("Adult"),
            output_field=CharField(),
        )
    )

def reverse_set_age_group(apps, schema_editor):
    PersonModel = apps.get_model("main_app", "Person")
    default = PersonModel._meta.get_field("age_group").default
    PersonModel.objects.update(age_group=default)



class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_person'),
    ]

    operations = [
        migrations.RunPython(set_age_group, reverse_set_age_group),
    ]

