# Generated by Django 5.0.4 on 2025-10-28 11:05

from django.db import migrations
from django.db.models import Case, When, Value, CharField


def set_item_rarity(apps, schema_editor):
    ItemModel = apps.get_model("main_app", "Item")

    ItemModel.objects.update(
        rarity=Case(
            When(price__lte=10, then=Value("Rare")),
            When(price__range=(11, 20), then=Value("Very Rare")),
            When(price__range=(21, 30), then=Value("Extremely Rare")),
            default=Value("Mega Rare"),
            output_field=CharField(),
        )
    )

def reverse_item_rarity(apps, schema_editor):
    ItemModel = apps.get_model("main_app", "Item")
    default = ItemModel._meta.get_field("rarity").default
    ItemModel.objects.update(rarity=default)





class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_item'),
    ]

    operations = [
        migrations.RunPython(
            code=set_item_rarity,
            reverse_code=reverse_item_rarity
        )
    ]
