# Generated by Django 5.0.4 on 2025-10-28 13:28

from django.db import migrations

def set_price(apps, schema_editor):
    SmartphoneModel = apps.get_model("main_app", "Smartphone")

    phones = []

    for p in SmartphoneModel.objects.all():
        p.price = len(p.brand) * 120
        phones.append(p)

    SmartphoneModel.objects.bulk_update(phones, ["price"])

def set_category(apps, schema_editor):
    SmartphoneModel = apps.get_model("main_app", "Smartphone")

    phones_to_update = []

    for p in SmartphoneModel.objects.all():
        if p.price <= 750:
            p.category = "Cheap"
        else:
            p.category = "Expensive"

        phones_to_update.append(p)

    SmartphoneModel.objects.bulk_update(phones_to_update, ["category"])

def set_fields(apps, schema_editor):
    set_price(apps, schema_editor)
    set_category(apps, schema_editor)

def reverse_fields(apps, schema_editor):
    SmartphoneModel = apps.get_model("main_app", "Smartphone")
    category_default = SmartphoneModel._meta.get_fields('category').default
    price_default = SmartphoneModel._meta.get_fields('price').default

    phones_to_update = []

    for p in SmartphoneModel.objects.all():
        p.category = category_default
        p.price = price_default
        phones_to_update.append(p)


    SmartphoneModel.objects.bulk_update(phones_to_update, ["category", "price"])



class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0013_smartphone'),
    ]

    operations = [
        migrations.RunPython(
            code=set_fields,
            reverse_code=reverse_fields
        )
    ]
