# Generated by Django 5.0.4 on 2025-10-28 20:56
from datetime import timedelta

from django.db import migrations
from django.db.models import Case, When, Value, F, CharField, DateField



def get_order_status(apps, schema_editor):
    OrderModel = apps.get_model("main_app", "Order")

    PENDING = 'Pending'
    COMPLETED = 'Completed'
    CANCELLED = 'Cancelled'

    OrderModel.objects.filter(status=PENDING).update(
        delivery=F('order_date') + timedelta(days=3)
    )

    OrderModel.objects.filter(status=COMPLETED).update(
        warranty="24 months"
    )

    OrderModel.objects.filter(status=CANCELLED).delete()


def reverse_get_order_status(apps, schema_editor):
    OrderModel = apps.get_model("main_app", "Order")
    default_delivery = OrderModel._meta.get_field('delivery').default
    default_warranty = OrderModel._meta.get_field('warranty').default

    OrderModel.objects.update(
        delivery=default_delivery,
        warranty=default_warranty
    )


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0015_order'),
    ]

    operations = [
        migrations.RunPython(
            code=get_order_status,
            reverse_code=reverse_get_order_status
        )
    ]